### ISSUE TITLE
Poor performance when working with the "Better search views" plugin

### ISSUE THREAD

**Issue by cakechaser** [mnaoumov/obsidian-backlink-cache#3]
Hi!

First of all thanks for the plugin, great idea, and it speeds up performance significantly.

I'm using the plugin https://github.com/ivan-lednev/better-search-views for better rendering of backlinks, and I noticed that with this plugin enabled I don't see any performance gains.

Timings for a file with ~100 backlinks:
|"Better Search Views" enabled?|"Backlink Cache" enabled?|Time to load backlinks|
|---|---|---|
|✅|✅|12s|
|❌|✅|1s|

I assume this might be because the "Better Search Views" plugin is not using the custom logic implemented in this plugin.

Would it be possible to somehow force other plugins to use the "cached" version of the logic from this plugin, which gets the backlinks?

It would be more convenient and would not require other developers to update their plugins to get the speed improvements.

Thanks!

**Comment by mnaoumov** [comment]
I checked the code of `better-search-views`, and it doesn't use any specifics about `Backlink View`. It just injects into Obsidian View generation logic. The slow part is not the calculation of `backlinks` which is super fast because of my plugin. The slow part is the rendering of the views, which my plugin has nothing to do with

**Comment by mnaoumov** [comment]
The slowness comes from how Better Search Views renders the backlink view, not from computing backlinks, which this plugin already makes fast. So there is nothing to change here.
